from .cat import Cat
from .dog import Dog
from .fish import Fish
from .goat import Goat
from .horse import Horse
from .lizard import Lizard
from .llama import Llama
from .pig import Pig
from .sheep import Sheep
from .snake import Snake