from .animals import (Cat, 
                    Dog, 
                    Fish, 
                    Goat, 
                    Horse, 
                    Lizard, 
                    Llama, 
                    Pig, 
                    Sheep, 
                    Snake)